[id='authorization-cli-user-create_{context}']
= Creating roles with custom permissions at runtime

Use {brandname} CLI to create custom authorization roles with different permissions.
{brandname} uses the default Cluster permission mapper to associate security principals to authorization roles defined at runtime.
Data about dynamically created roles is stored in the persistent data directory.

.Prerequisites

* Have a {brandname} user with `admin` permissions.

.Procedure

. Create a CLI connection to {brandname}.
. Define a role with set of permissions.
+
[source,bash,options="nowrap",subs=attributes+]
----
[//containers/default]> user roles create --permissions=ALL_WRITE,LISTEN myroleone
[//containers/default]> user roles create --permissions=READ,WRITE myroletwo
----
. Assign roles to a user.
+
[source,bash,options="nowrap",subs=attributes+]
----
[//containers/default]> user roles grant --roles=myroleone myroletwo username
----

.Verification

. List roles associated with the user.
+
[source,bash,options="nowrap",subs=attributes+]
----
[//containers/default]> user roles ls username
----
. Use the CLI or the {brandname} Console to perform operations and test that you have the required permissions.

.Next steps
* Remove any roles that you created for a temporary purpose.
+
[source,bash,options="nowrap",subs=attributes+]
----
[//containers/default]> user roles deny --roles=myroleone, myroletwo username
[//containers/default]> user remove roles myroleone myroletwo
----
